### PR TITLE
[Fix-310][gateway]Configure hadoop_conf for Flink

### PR DESCRIPTION
**Pull request by SunDapeng1**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by SunDapeng1** [comment]
#310

**Comment by aiwenmo** [comment]
1.Please build PR based on Dev and submit it to dev.

**Comment by aiwenmo** [comment]
2.'fs.hdfs.hadoopconf' is deprecated in 1.12 and 1.13, and deleted in 1.14.

**Comment by aiwenmo** [comment]
3.Please find a more suitable configuration. thx

**Comment by SunDapeng1** [comment]
> 1.Please build PR based on Dev and submit it to dev.

do it in #316 , and close 
 

> 2.'fs.hdfs.hadoopconf' is deprecated in 1.12 and 1.13, and deleted in 1.14.
> 3.Please find a more suitable configuration. thx

In the latest Flink, it seems that there is not a more suitable configuration, as shown in #316.
can you give me some suggestion? thx

**Pull request closed without merging**
