### PR TITLE
[Fix-491][admin,web] Fix refresh the status page with abnormal jitter

### PR DESCRIPTION
**Pull request by wmtbnbo**
[Fix-491][admin,web] Fix refresh the status page with abnormal jitter

## Purpose of the pull request

Fix bug refresh the status page with abnormal jitter #491 

## Brief change log

dlink-admin/src/main/java/com/dlink/model/JobInstance.java add @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")

## Verify this pull request

This pull request is code cleanup without any test coverage.

no

This pull request is already covered by existing tests, such as *(please describe tests)*.

no

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by aiwenmo** [comment]
Please commit into dev

**Comment by wmtbnbo** [comment]
> Please commit into dev

已调整到dev

**Comment by aiwenmo** [comment]
请从您的本地仓库的dev提交至开源仓库dev，只包含更改的 commit，理论上 commit 数只有 1

**Comment by wmtbnbo** [comment]
> 请从您的本地仓库的dev提交至开源仓库dev，只包含更改的 commit，理论上 commit 数只有 1

好的，我调整一下，重新发起

**Pull request closed without merging**
