### PR TITLE
add docker support

### PR DESCRIPTION
**Pull request by SIvaCoHan**
## Purpose of the pull request

增加docker支持

## Brief change log

packge打包操作
```
docker-compose build
```

启动dinky服务
```
docker-compose up
```

## Verify this pull request
启动了大概这样
访问 http://localhost:8080/ 即可
Screen Shot 2022-04-06 at 4 11 14 PM

### CODE REVIEW

**Comment by aiwenmo** [comment]
请提交到dev分支

**Comment by SIvaCoHan** [comment]
> 

Done

**Comment by walkhan** [comment]
> > 
> 
> Done


Hi, can you contribute to the documentation of docker compilation and installation of dinky?

**Comment by SIvaCoHan** [comment]
> 

Can you give a table of content? I have no idea about what should be write down.

**Comment by aiwenmo** [comment]
> > 
> 
> Can you give a table of content? I have no idea about what should be write down.

https://dolphinscheduler.apache.org/zh-cn/docs/latest/user_doc/guide/start/docker.html

**Comment by SIvaCoHan** [comment]
Ok, wait a little bit. It takes time to write a useful doc.

**Pull request merged**
