### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by gaopan-05**
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

### CODE REVIEW

**Comment by walkhan** [comment]
@gaopan-05 Hi,Do you have this problem with cloning other open source projects? If other open source projects do not, consider whether it is necessary?

**Comment by walkhan** [comment]
@gaopan-05 You can try using a VPN

**Comment by gaopan-05** [comment]
> 



> @gaopan-05 You can try using a VPN

Ok,I just test my first PR at the same time ,sorry

**Comment by aiwenmo** [comment]
> > 
> 
> > @gaopan-05 You can try using a VPN
> 
> Ok,I just test my first PR at the same time ,sorry

PTAL, good first issue

**Comment by walkhan** [comment]
@gaopan-05 Another solution is that you have to ssh.After adding your local ssh key to github, it should be better to go through ssh PR

**Comment by gaopan-05** [comment]
> @gaopan-05 Another solution is that you have to ssh.After adding your local ssh key to github, it should be better to go through ssh PR

This problem occurred during the Clone process

**Comment by walkhan** [comment]
@gaopan-05 This is a network problem, cloning can also be done through ssh

**Comment by gaopan-05** [comment]
> @gaopan-05 This is a network problem, cloning can also be done through ssh

ok

**Pull request closed without merging**
